openapi: 3.0.3
info:
  description: >-
    <b>"SIM PROVISION"</b></br>
    Porpuse: For activation of a subscriber, we need to have the functionality to pre-provision a SIM card first.
    
    
    <br> Currently this api contains following methods.
    <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
      <tr align="Left">
        <th>Method Name</th>
        <th>Description</th>
      </tr>
      <tr>
        <td><b><i>Provision</i></b></td>
        <td> This method provides ability to use this API during pre-provisioning of the SIM cards in case of error scenarios during initial run during the file upload.</td>
      </tr>
      <tr>
        <td><b><i>Bulk Provision</i></b></td>
        <td> This is the automated flow. Once the File is loaded in the document DB via Lambda, the Lambda will call this API and use the same to pre-provision in the relevant core for the environment.</td>
      </tr>
      <tr>
        <td><b><i>Get Provision</i></b></td>
        <td> This API is used to search a list of ICCID/IMSI provided by the filename as an input. So that any irregularities can be fetched for the same</td>
      </tr>
      <tr>
        <td><b><i>Search Provision</i></b></td>
        <td> This API is used to search any filename provided by the ICCID/IMSI/FIMSI1/FIMSI2 as an input. So that any discrepancies can be fetched for the same</td>
      </tr>
      <tr>
        <td><b><i>Get Statistics</i></b></td>
        <td> This method provides ability to get simDataDetails statistics. Can get count of fileNames, iccid, imsi and provisionFlag from simDataDetails. Also get all records to see infomation of each record.</td>
      </tr>
    </table><br>
  version: 1.0.0
  title: "DSIM Serverless :: SIM PROVISION"
  license:
    name: DISH Internal Use Only
    url: https://dish.com
tags:
  - name: SIM Provision
  - name: SIM Statistics
paths:
  /provision:
    post:
      tags:
        - SIM Provision
      summary: >-
        Performs a sim provision to a device (Single AUC pre-provision)
      requestBody:
        $ref: '#/components/requestBodies/provision'
      responses:
        '200':
          $ref: '#/components/responses/provision200'
        '500':
          $ref: '#/components/responses/provision500'
  /bulkProvision:
    post:
      tags:
        - SIM Provision
      summary: >-
        Performs pre provisions the bulk SIM on Nokia Core
      requestBody:
        $ref: '#/components/requestBodies/bulkProvision'
      responses:
        '200':
          $ref: '#/components/responses/bulkProvision200'
        '500':
          $ref: '#/components/responses/bulkProvision500'
  /getProvision:
    post:
      tags:
        - SIM Provision
      summary: >-
        Performs a sim getProvision to a device
      requestBody:
        $ref: '#/components/requestBodies/simGetProvision'
      responses:
        '200':
          $ref: '#/components/responses/simGetProvision200'
  /searchProvision:
    post:
      tags:
        - SIM Provision
      summary: >-
        Performs a sim searchProvision to a device
      requestBody:
        $ref: '#/components/requestBodies/searchProvision'
      responses:
        '200':
          $ref: '#/components/responses/searchProvision200'
  /getStatistics:
    post:
      tags:
        - SIM Statistics
      summary: >-
        Performs a sim Statistics to a sim data details DB
      requestBody:
        $ref: '#/components/requestBodies/getStatistics'
      responses:
        '200':
          $ref: '#/components/responses/getStatistics200'
security:
  - basicAuth: []

components:
  securitySchemes:
    basicAuth: # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  requestBodies:
    provision:
      description: >-
        <b> This is the model of provision request </b>
        <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
          <tr align="Left">
            <th>Body field</th>
            <th>Data type</th>
            <th>Cardinality</th>
            <th>Description</th>
          </tr>
          <tr>
            <td><b><i>iccid</i></b></td>
            <td>String</td>
            <td>Mandatory</td>
            <td>The Integrated Circuit Card Identification number (ICCID) is an 19-20-digit number typically printed on the back of a SIM card.</td>
          </tr>
          <tr>
            <td><b><i>imsi</i></b></td>
            <td>String</td>
            <td>Mandatory</td>
            <td>International Mobile Subscriber Identity, IMSI, is a unique number automatically generated and stored in the SIM</td>
          </tr>
          <tr>
            <td><b><i>environment</i></b></td>
            <td>String</td>
            <td>Optional</td>
            <td>Environment Values pre-defined in the config table.</td>
          </tr>
        </table></br>
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/simProvision'
          examples:
            simProvisionEnvSuccessRequest:
              $ref: '#/components/examples/simProvisionEnvSuccessRequest'
            simProvisionSuccessRequest:
              $ref: '#/components/examples/simProvisionSuccessRequest'
            simProvisionFailureInvalidDataRequest:
              $ref: '#/components/examples/simProvisionFailureInvalidDataRequest'
            simProvisionFailureMissingParameterRequest:
              $ref: '#/components/examples/simProvisionFailureMissingParameterRequest'
      required: true
    bulkProvision:
      description: >-
        <b> This is the model of bulkProvision request </b>
        <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
          <tr align="Left">
            <th>Body field</th>
            <th>Data type</th>
            <th>Cardinality</th>
            <th>Description</th>
          </tr>
          <tr>
            <td><b><i>fileName</i></b></td>
            <td>String</td>
            <td>Mandatory</td>
            <td>File name to perform bulk povision.</td>
          </tr>
          <tr>
            <td><b><i>environment</i></b></td>
            <td>String</td>
            <td>Optional</td>
            <td>Environment Values pre-defined in the config table.</td>
          </tr>
        </table></br>
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/simBulkProvision'
          examples:
            simBulkProvisionEnvSuccessRequest:
              $ref: '#/components/examples/simBulkProvisionEnvSuccessRequest'
            simBulkProvisionSuccessRequest:
              $ref: '#/components/examples/simBulkProvisionSuccessRequest'
      required: true
    simGetProvision:
      description: >-
        <b> This is the model of getProvision request </b>
        <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
          <tr align="Left">
            <th>Body field</th>
            <th>Data type</th>
            <th>Cardinality</th>
            <th>Description</th>
          </tr>
          <tr>
            <td><b><i>fileName</i></b></td>
            <td>String</td>
            <td>Mandatory</td>
            <td>File name to perform bulk povision.</td>
          </tr>
          <tr>
            <td><b><i>environment</i></b></td>
            <td>String</td>
            <td>Optional</td>
            <td>Environment Values pre-defined in the config table.</td>
          </tr>
        </table></br>
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/simGetProvision'
          examples:
            simGetProvisionSuccessRequest:
              $ref: '#/components/examples/simGetProvisionSuccessRequest'
            simGetProvisionSuccessRequestNoEnv:
              $ref: '#/components/examples/simGetProvisionSuccessRequestNoEnv'
      required: true
    searchProvision:
      description: >-
        <p>This API is used to search any fileName provided by the ICCID/IMSI/FIMSI1/FIMSI2 as an input<p>
        <b> This is the model of searchProvision request </b></br>
        <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
          <tr align="Left">
            <th>Body field</th>
            <th>Data type</th>
            <th>Cardinality</th>
            <th>Description</th>
          </tr>
          <tr>
            <td><b><i>iccid</i></b></td>
            <td>Array of Strings</td>
            <td>Conditional</td>
            <td>Array of iccid to get sim data details</td>
          </tr>
          <tr>
            <td><b><i>imsi</i></b></td>
            <td>Array of Strings</td>
            <td>Conditional</td>
            <td>Array of imsi to get sim data details.</td>
          </tr>
          <tr>
            <td><b><i>fimsi1</i></b></td>
            <td>Array of Strings</td>
            <td>Conditional</td>
            <td>Array of fimsi1 to get sim data details.</td>
          </tr>
          <tr>
            <td><b><i>fimsi2</i></b></td>
            <td>Array of Strings</td>
            <td>Conditional</td>
            <td>Array of fimsi2 to get sim data details.</td>
          </tr>
        </table></br>
        <p> Out of 4 keys anyone should be present<p>
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/searchProvision'
          examples:
            simSearchProvisionSuccessRequestIccid:
              $ref: '#/components/examples/simSearchProvisionSuccessRequestIccid'
            simSearchProvisionSuccessRequestImsi:
              $ref: '#/components/examples/simSearchProvisionSuccessRequestImsi'
            simSearchProvisionSuccessRequestFimsi1:
              $ref: '#/components/examples/simSearchProvisionSuccessRequestFimsi1'
            simSearchProvisionSuccessRequestFimsi2:
              $ref: '#/components/examples/simSearchProvisionSuccessRequestFimsi2'
      required: true
    getStatistics:
      description:
        <b> This is the model of getStatistics request </b>
        <table style="box-shadow:none;padding:0 0 0 0;margin:0;" border="1px">
          <tr align="Left">
            <th>Body field</th>
            <th>Data type</th>
            <th>Cardinality</th>
            <th>Description</th>
          </tr>
          <tr>
            <td><b><i>fileNameCountRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return fileName count from sim data db</td>
          </tr>
          <tr>
            <td><b><i>fileNameRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return fileName from sim data</td>
          </tr>
          <tr>
            <td><b><i>iccidCountRequired</i></b></td>
            <td>Boolean</td>
            <td>Optional</td>
            <td>Return iccid count from sim data db</td>
          </tr>
          <tr>
            <td><b><i>iccidRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return iccid from sim data</td>
          </tr>
          <tr>
            <td><b><i>imsiCountRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return imsi count from sim data db</td>
          </tr>
          <tr>
            <td><b><i>imsiRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return imsi from sim data</td>
          </tr>
          <tr>
            <td><b><i>provisionedFlagCountRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return provisionedFlag count from sim data db</td>
          </tr>
          <tr>
            <td><b><i>provisionedFlagRequired</i></b></td>
            <td>Boolean</td>
            <td>Mandatory</td>
            <td>Return provisionedFlag from sim data</td>
          </tr>
          <tr>
            <td><b><i>page</i></b></td>
            <td>Interger</td>
            <td>Mandatory</td>
            <td>Should be greater than 0</td>
          </tr>
          <tr>
            <td><b><i>size</i></b></td>
            <td>Interger</td>
            <td>Mandatory</td>
            <td>Should be greater than 0</td>
          </tr>
        </table></br>
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getStatistics'
          examples:
            getStatisticsSuccessCount:
              $ref: '#/components/examples/getStatisticsRequestSuccessCount'
            getStatisticsRequestSuccessNonCount:
              $ref: '#/components/examples/getStatisticsRequestSuccessNonCount'
            getStatisticsRequestSuccessCountNonCount:
              $ref: '#/components/examples/getStatisticsRequestSuccessCountNonCount'
  responses:
    provision200:
      description: >-
        This represents model of 200 response for provision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/provisionResponse'
          examples:
            provisionResponse200success:
              $ref: '#/components/examples/provisionResponse200success'
            getProfileTypeResponseErrorAlreadyProvisioned:
              $ref: '#/components/examples/provisionResponse200AlreadyProvisioned'
            getProfileTypeResponseErrorProvisionedNokiaPGW:
              $ref: '#/components/examples/provisionResponse200ProvisionedNokiaPGW'
            getProfileTypeResponseErrorSIMDetailsNotFound:
              $ref: '#/components/examples/provisionResponse200SIMDetailsNotFound'
            getProfileTypeResponseErrorEnvironmentNotConfigured:
              $ref: '#/components/examples/provisionResponse200EnvironmentNotConfigured'
            getProfileTypeResponseErrorScenarioNokiaPGW:
              $ref: '#/components/examples/provisionResponse200ErrorScenarioNokiaPGW'
            getProfileTypeResponseErrorEnvironmentConfigurationMissing:
              $ref: '#/components/examples/provisionResponse200ErrorEnvironmentConfigurationMissing'
            getProfileTypeResponseErrorInvalidData:
              $ref: '#/components/examples/provisionResponse200ErrorInvalidData'
            getProfileTypeResponseErrorMandatoryParameterMissing:
              $ref: '#/components/examples/provisionResponse200ErrorMandatoryParameterMissing'
    provision500:
      description: >-
        This represents model of 500 response for provision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/provisionResponse'
          examples:
            provisionResponse500:
              $ref: '#/components/examples/provisionResponse500'
    bulkProvision200:
      description: >-
        This represents model of 200 response for bulkProvision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bulkProvisionResponse'
          examples:
            bulkProvisionResponse200success:
              $ref: '#/components/examples/bulkProvisionResponse200success'
            bulkProvisionResponse200provisioned:
              $ref: '#/components/examples/bulkProvisionResponse200provisioned'
    bulkProvision500:
      description: >-
        This represents model of 500 response for bulkProvision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/bulkProvisionResponse'
          examples:
            bulkProvisionResponse500:
              $ref: '#/components/examples/bulkProvisionResponse500'
    simGetProvision200:
      description: >-
        This represents model of 200 response for getProvision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getProvisionResponse'
          examples:
            getProvisionResponse200success:
              $ref: '#/components/examples/getProvisionResponse200success'
            getProvisionResponse200NoFileName:
              $ref: '#/components/examples/getProvisionResponse200NoFileName'
            getProvisionResponse200NoFileNameFound:
              $ref: '#/components/examples/getProvisionResponse200NoFileNameFound'
    searchProvision200:
      description: >-
        This represents model of 200 response for searchProvision
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/searchProvisionResponse'
          examples:
            searchProvisionResponse200success:
              $ref: '#/components/examples/searchProvisionResponse200success'
            searchProvisionResponse200NoFileName:
              $ref: '#/components/examples/searchProvisionResponse200Error'
    getStatistics200:
      description: >-
        This represent model of 200 response for getStatistics
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getStatisticsResponse200'
          examples:
            getStatisticsResponse200Count:
              $ref: '#/components/examples/getStatisticsResponse200Count'
            getStatisticsResponse200NonCount:
              $ref: '#/components/examples/getStatisticsResponse200NonCount'
            getStatisticsResponse200CountNonCount:
              $ref: '#/components/examples/getStatisticsResponse200CountNonCount'
  schemas:
    simProvision:
      properties:
        environment:
          $ref: '#/components/schemas/environment'
        imsi:
          $ref: '#/components/schemas/imsi'
        iccid:
          $ref: '#/components/schemas/iccid'
    provisionResponse:
      title: Provision response 200 model
      description: This represents the model of provision 200 response
      type: object
      properties:
        result:
          type: string
          description: result status
          example: success
        imsi: 
          $ref: '#/components/schemas/imsi'
        iccid:
          $ref: '#/components/schemas/iccid'
        error:
          $ref: '#/components/schemas/error'
    simBulkProvision:
      properties:
        fileName:
          type: string
          description: fileName
          example: 'DEV'
        environment:
          $ref: '#/components/schemas/environment'
    bulkProvisionResponse:
      properties:
        result:
          type: string
          description: result status
          example: 'success'
        message:
          type: string
          example: The file "fileName" is getting processed
        error:
          $ref: '#/components/schemas/error'
    simGetProvision:
      properties:
        environment:
          $ref: '#/components/schemas/environment'
        fileName:
          type: string
          description: sim bulk provision file name.
          example: 'DW000148_DW5G100TSIME_04242024_MNO.OUT'
    getProvisionResponse:
      title: getProvision response schema
      description: This represent the model of getProvision response
      type: array
      items: 
        type: object
        example:
          - id: '313340200004326_89105110012000043268'
            imsi: '313340200004326'
            iccid: '89105110012000043268'
            encKey: F6119A937E06D5864E453AA73AB75013
            algoId: '3'
            kdbId: '3'
            acsub: '2'
            amf: '0000'
            sqn: '000000000000'
            fileName: DIS00051_MNO.out
            provisioned: N
    searchProvision:
      properties:
        imsi:
          type: array
          description: Array of imsi to search
          items: 
            $ref: '#/components/schemas/imsi'
        iccid:
          type: array
          description: Array of iccid to search
          items:
            $ref: '#/components/schemas/iccid'
        fimsi1:
          type: array
          description: Array of fimsi1 to search
          items:
            type: string
            description: Foreign International Mobile Subscriber Identity.
            example: '313340200445678'
        fimsi2:
          type: array
          description: Array of fimsi2 to search
          items:
            type: string
            description: Foreign International Mobile Subscriber Identity.
            example: '313340200445678'
    searchProvisionResponse:
      title: searchProvision response schema
      description: This represent the model of searchProvision response
      type: array
      items: 
        type: object
        description: Object with sim data details
        example:
          - id: '313340200004326_89105110012000043268'
            imsi: '313340200004326'
            iccid: '89105110012000043268'
            encKey: F6119A937E06D5864E453AA73AB75013
            algoId: '3'
            kdbId: '3'
            acsub: '2'
            amf: '0000'
            sqn: '000000000000'
            fileName: DIS00051_MNO.out
            provisioned: N
    searchProvisionResponse400:
      title: searchProvision 400 response schema
      description: This represent the model of searchProvision response
      type: array
      properties:
        result: 
          type: string
          description: result status
          example: 'failure'
        error:
          $ref: '#/components/schemas/error'
    getStatistics:
      title: getStatistics request model
      description: This represents the model of getStatistics request
      type: object
      properties:
        fileNameCountRequired:
          type: boolean
          example: true
        fileNameRequired:
          type: boolean
          example: true
        iccidCountRequired:
          type: boolean
          example: true
        iccidRequired:
          type: boolean
          example: true
        imsiCountRequired:
          type: boolean
          example: true
        imsiRequired:
          type: boolean
          example: true
        provisionedFlagCountRequired:
          type: boolean
          example: true
        provisionedFlagRequired:
          type: boolean
          example: true
        page:
          type: string
          example: 1
        size:
          type: string
          example: 10
    getStatisticsResponse200:
      title: getStatistics response model
      description: This represents the model of getStatistics response
      type: object
      properties:
        result:
          type: string
          description: result status
          example: success
        currentPage:
          type: integer
          description: currente page number
          example: 1
        totalDocuments:
          type: integer
          description: Number of records in db that match request
          example: 108
        data:
          type: array
          description: array with response data
          items:
            type: object
            description: Object with data count or sim datails
          example: 
            - fileName: DW000064_DW5G100DSIME_04282022_MNO.OUT
              provisionedFlag: 
              iccid: 
              imsi: 
              fileNameCount: 0
              provisionedFlagCount: 1(N)
              iccidCount: 5
              imsiCount: 5
    environment:
      type: string
      description: environment.
      example: 'DEV'
    iccid:
      type: string
      description: Integrated Circuit Card ID, length should be 19 or 20-digit.
      example: '89105110010790056391'
    imsi:
      type: string
      description: International Mobile Subscriber Identity.
      example: '313340200445678'
    error:
      type: object
      description: Error Object
      example:
        error:
          errorCode: SIMXXX
          errorMessage: XXXXXXX
  examples:
    simProvisionEnvSuccessRequest:
      summary: Success scenario
      value:
        environment: 'DEV'
        imsi: '313340999969501'
        iccid: '89105199919999695011'
    simProvisionSuccessRequest:
      summary: Success scenario without Environment
      value:
        imsi: '313340999969501'
        iccid: '89105199919999695011' 
    simProvisionFailureInvalidDataRequest:
      summary: Failure scenario, invalid data
      value:
        imsi: 313340999969501
        iccid: '89105199919999695011' 
    simProvisionFailureMissingParameterRequest:
      summary: Failure scenario, missing parameter
      value:
        iccid: '89105199919999695011' 
    provisionResponse200success:
      summary: success scenario
      value:
        result: success
        imsi: '313340999969501'
        iccid: '89105199919999695011'
    provisionResponse200AlreadyProvisioned:
      summary: Already Provisioned
      value:
        error: 
          code: SIM005
          message: 'SIM Card Already Provisioned as per Transactional Data'
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200ProvisionedNokiaPGW:
      summary: Already Provisioned in Nokia PGW
      value:
        error: 
          code: '68'
          message: 'error result (68) Key already exists: imsi'
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200SIMDetailsNotFound:
      summary: SIM Details not Found
      value:
        error:
          code: SIM005
          message: Sim Data does not exist
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200EnvironmentNotConfigured:
      summary: Environment Not Configured
      value:
        error:
          code: SIM005
          message: Requested environment not configured.
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200ErrorScenarioNokiaPGW:
      summary: Error Scenario from Nokia PGW
      value:
        error:
          code: XX
          message: "<Actual Error response from Nokia>"
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200ErrorEnvironmentConfigurationMissing:
      summary: Environment Configuration missing
      value:
        error:
          code: SIM005
          message: Environment Configuration Missing
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200ErrorInvalidData:
      summary: Invalid Data
      value:
        error:
          code: SIM002
          message: Invalid Data
        result: failure
        imsi: '313340999969500'
        iccid: '89105199919999695003'
    provisionResponse200ErrorMandatoryParameterMissing:
      summary: Mandatory Parameter Missing
      value:
        result: failure
        error:
          code: SIM003
          message: Mandatory Parameter Missingiccid/imsi
        imsi: '313340999969502'
        iccid: '89105199919999695012'
    provisionResponse500:
      summary: Internal Error
      value: 
        result: failure
        error:
          code: SIM004
          message: Internal Server Error
        imsi: '313340999969502'
        iccid: '89105199919999695012'
    simBulkProvisionEnvSuccessRequest:
      summary: Success scenario with env
      value:
        fileName: 'DW000148_DW5G100TSIME_04242024_MNO.OUT'
        environment: 'DEV'
    simBulkProvisionSuccessRequest:
      summary: Success scenario without env
      value:
        fileName: 'DW000148_DW5G100TSIME_04242024_MNO.OUT'
    bulkProvisionResponse200success:
      summary: Success scenario
      value:
        result: success
        message: The file DW000148_DW5G100TSIME_04242024_MNO.OUT is getting processed
    bulkProvisionResponse200provisioned:
      summary: Error Scenario Already Provisioned
      value:
        error:
          code: SIM005
          message: No Record found for sample.out with provisioned as N
        result: failure
        filename: DW000148_DW5G100TSIME_04242024_MNO.OUT
    bulkProvisionResponse500:
      summary: Internal error
      value:
        result: failure
        error:
          code: SPROV-XX
          message: Internal Server Error
        filename: DW000148_DW5G100TSIME_04242024_MNO.OUT
    simGetProvisionSuccessRequest:
      summary: Success request with env
      value:
        fileName: DW000148_DW5G100TSIME_04242024_MNO.OUT
        environment: DEV
    simGetProvisionSuccessRequestNoEnv:
      summary: Success request without env
      value:
        fileName: DW000148_DW5G100TSIME_04242024_MNO.OUT
    getProvisionResponse200success:
      summary: Success scenario
      value: 
        - id: '313340200004326_89105110012000043268'
          imsi: '313340200004326'
          iccid: '89105110012000043268'
          encKey: F6119A937E06D5864E453AA73AB75013
          algoId: '3'
          kdbId: '3'
          acsub: '2'
          amf: '0000'
          sqn: '000000000000'
          fileName: DIS00051_MNO.out
          provisioned: N
    getProvisionResponse200NoFileName:
      summary: No file name
      value:
        error:
          code: SIM003
          message: FileName Not Received
        result: failure
    getProvisionResponse200NoFileNameFound:
      summary: No file name found
      value:
        error:
          code: SIM005
          message: No Record found for Filename
        result: failure
    simSearchProvisionSuccessRequestIccid:
      summary: iccid request
      value:
        iccid:
          - '89105110011008235868'
          - '89105110011008735859'
    simSearchProvisionSuccessRequestImsi:
      summary: imsi request
      value:
        imsi:
          - '313340100823586'
          - '313340100873585'
    simSearchProvisionSuccessRequestFimsi1:
      summary: fimsi1 request
      value:
        fimsi1:
          - '208090074823586'
          - '208090074873585'
    simSearchProvisionSuccessRequestFimsi2:
      summary: fimsi2 request
      value:
        fimsi2:
          - '302220521823586'
          - '302220521873585'
    searchProvisionResponse200success:
      summary: Success response
      value:
        - id: '313340200004326_89105110012000043268'
          imsi: '313340200004326'
          iccid: '89105110012000043268'
          encKey: F6119A937E06D5864E453AA73AB75013
          algoId: '3'
          kdbId: '3'
          acsub: '2'
          amf: '0000'
          sqn: '000000000000'
          fileName: DIS00051_MNO.out
          provisioned: N
    searchProvisionResponse200Error:
      summary: Error response
      value:
        error:
          code: SIM002
          message: ICCID/IMSI/FIMSI1/FIMSI2 anyone should be sent
        result: failure
    getStatisticsRequestSuccessCount:
      summary: Count request
      value:
        fileNameCountRequired: true
        fileNameRequired: false
        iccidCountRequired: true
        iccidRequired: false
        imsiCountRequired: true
        imsiRequired: false
        provisionedFlagCountRequired: true
        provisionedFlagRequired: false
        page: 1
        size: 10
    getStatisticsRequestSuccessNonCount:
      summary: Non Count request
      value:
        fileNameCountRequired: false
        fileNameRequired: true
        iccidCountRequired: false
        iccidRequired: true
        imsiCountRequired: false
        imsiRequired: true
        provisionedFlagCountRequired: false
        provisionedFlagRequired: true
        page: 1
        size: 10
    getStatisticsRequestSuccessCountNonCount:
      summary: Count and Non Count request
      value:
        fileNameCountRequired: true
        fileNameRequired: true
        iccidCountRequired: true
        iccidRequired: false
        imsiCountRequired: true
        imsiRequired: false
        provisionedFlagCountRequired: false
        provisionedFlagRequired: false
        page: 1
        size: 10
    getStatisticsResponse200Count:
      summary: Count response
      value:
        result: success
        currentPage: 1
        totalDocuments: 1
        data:
        - fileName: 
          provisionedFlag: 
          iccid: 
          imsi: 
          fileNameCount: 54
          provisionedFlagCount: '215407'
          iccidCount: 215407
          imsiCount: 215407
    getStatisticsResponse200NonCount:
      summary: Non Count response
      value:
        result: success
        currentPage: 1
        totalDocuments: 215407
        data:
        - fileName: TIS00167_MNO.out
          provisionedFlag: N
          iccid: '89105110012001045684'
          imsi: '313340200104568'
          fileNameCount: 0
          provisionedFlagCount: 
          iccidCount: 0
          imsiCount: 0
        - fileName: TIS00167_MNO.out
          provisionedFlag: N
          iccid: '89105110012001045676'
          imsi: '313340200104567'
          fileNameCount: 0
          provisionedFlagCount: 
          iccidCount: 0
          imsiCount: 0
    getStatisticsResponse200CountNonCount:
      summary: Count and non Cont response
      value:
        result: success
        currentPage: 1
        totalDocuments: 108
        data:
        - fileName: DW000064_DW5G100DSIME_04282022_MNO.OUT
          provisionedFlag: 
          iccid: 
          imsi: 
          fileNameCount: 0
          provisionedFlagCount: 1(N)
          iccidCount: 5
          imsiCount: 5
